apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-kustomize-prod

resources:
  - ../dev

images:
  - name: nginx
    newTag: "1.25.2"

patchesStrategicMerge:
  - configmap-patch.yaml

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
